---
- name: Delete a VLAN on JTCom switch
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    switch_host: 192.0.2.1
    switch_user: "{{ lookup('env', 'SWITCH_USER') | default('admin') }}"
    switch_pass: "{{ lookup('env', 'SWITCH_PASS') }}"

  tasks:
    - name: Remove VLAN 99 if it exists
      bronweg.cgiswitch.jtcom_config:
        host: "{{ switch_host }}"
        username: "{{ switch_user }}"
        password: "{{ switch_pass }}"
        verify_tls: false
        vlans:
          99:
            state: absent
